// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWF6kVzye9UkR_VN5RXYXi3skaQN7cxuk',
    appId: '1:425207283481:web:4be59b2edc59d437ab4f88',
    messagingSenderId: '425207283481',
    projectId: 'todo-app-857d0',
    authDomain: 'todo-app-857d0.firebaseapp.com',
    storageBucket: 'todo-app-857d0.firebasestorage.app',
    measurementId: 'G-FSLWSSQL8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbiU51WmMZHHVAK_sY4zSEvmIXCf1Iexg',
    appId: '1:425207283481:android:d2bc13e0506f90d4ab4f88',
    messagingSenderId: '425207283481',
    projectId: 'todo-app-857d0',
    storageBucket: 'todo-app-857d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCx75NOdXQuUaPaEMI3sOosaI-wgz5PVk',
    appId: '1:425207283481:ios:cf5bbdfbe306dc6dab4f88',
    messagingSenderId: '425207283481',
    projectId: 'todo-app-857d0',
    storageBucket: 'todo-app-857d0.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCx75NOdXQuUaPaEMI3sOosaI-wgz5PVk',
    appId: '1:425207283481:ios:cf5bbdfbe306dc6dab4f88',
    messagingSenderId: '425207283481',
    projectId: 'todo-app-857d0',
    storageBucket: 'todo-app-857d0.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWF6kVzye9UkR_VN5RXYXi3skaQN7cxuk',
    appId: '1:425207283481:web:56252390f96126c0ab4f88',
    messagingSenderId: '425207283481',
    projectId: 'todo-app-857d0',
    authDomain: 'todo-app-857d0.firebaseapp.com',
    storageBucket: 'todo-app-857d0.firebasestorage.app',
    measurementId: 'G-5CFVMV5DFX',
  );
}
